import { User } from './types';

// Small team example (5-10 people)
export const smallTeamData: User[] = [
  {
    id: '1',
    name: 'Sarah Chen',
    email: 'sarah.chen@company.com',
    jobRole: 'P',
    manager: null,
    about: 'Partner leading the consulting practice',
    profilePicture: undefined,
  },
  {
    id: '2',
    name: 'Michael Roberts',
    email: 'michael.roberts@company.com',
    jobRole: 'SM',
    manager: '1',
    about: 'Senior Manager overseeing client delivery',
  },
  {
    id: '3',
    name: 'Emily Watson',
    email: 'emily.watson@company.com',
    jobRole: 'M',
    manager: '2',
    about: 'Manager focused on digital transformation projects',
  },
  {
    id: '4',
    name: 'David Kim',
    email: 'david.kim@company.com',
    jobRole: 'SC1',
    manager: '3',
    about: 'Senior Consultant specializing in cloud architecture',
  },
  {
    id: '5',
    name: 'Lisa Anderson',
    email: 'lisa.anderson@company.com',
    jobRole: 'SC2',
    manager: '3',
    about: 'Senior Consultant with expertise in data analytics',
  },
  {
    id: '6',
    name: 'James Taylor',
    email: 'james.taylor@company.com',
    jobRole: 'C3',
    manager: '3',
    about: 'Consultant working on enterprise solutions',
  },
];

// Medium team with multiple branches
export const mediumTeamData: User[] = [
  {
    id: '1',
    name: 'Alexandra Martinez',
    email: 'alexandra.martinez@company.com',
    jobRole: 'P',
    manager: null,
    about: 'Partner and Managing Director',
  },
  {
    id: '2',
    name: 'Robert Chang',
    email: 'robert.chang@company.com',
    jobRole: 'SM',
    manager: '1',
    about: 'Senior Manager - Technology Practice',
  },
  {
    id: '3',
    name: 'Jennifer Williams',
    email: 'jennifer.williams@company.com',
    jobRole: 'SM',
    manager: '1',
    about: 'Senior Manager - Strategy Practice',
  },
  {
    id: '4',
    name: 'Thomas Brown',
    email: 'thomas.brown@company.com',
    jobRole: 'M',
    manager: '2',
    about: 'Manager - Cloud Solutions',
  },
  {
    id: '5',
    name: 'Maria Garcia',
    email: 'maria.garcia@company.com',
    jobRole: 'M',
    manager: '2',
    about: 'Manager - Application Development',
  },
  {
    id: '6',
    name: 'Christopher Lee',
    email: 'christopher.lee@company.com',
    jobRole: 'M',
    manager: '3',
    about: 'Manager - Business Strategy',
  },
  {
    id: '7',
    name: 'Amanda White',
    email: 'amanda.white@company.com',
    jobRole: 'SC2',
    manager: '4',
    about: 'Senior Consultant - DevOps',
  },
  {
    id: '8',
    name: 'Daniel Harris',
    email: 'daniel.harris@company.com',
    jobRole: 'SC1',
    manager: '4',
    about: 'Senior Consultant - Infrastructure',
  },
  {
    id: '9',
    name: 'Rachel Thompson',
    email: 'rachel.thompson@company.com',
    jobRole: 'C3',
    manager: '4',
    about: 'Consultant - Cloud Migration',
  },
  {
    id: '10',
    name: 'Kevin Martinez',
    email: 'kevin.martinez@company.com',
    jobRole: 'SC2',
    manager: '5',
    about: 'Senior Consultant - Full Stack Development',
  },
  {
    id: '11',
    name: 'Sophie Anderson',
    email: 'sophie.anderson@company.com',
    jobRole: 'C2',
    manager: '5',
    about: 'Consultant - Frontend Development',
  },
  {
    id: '12',
    name: 'Marcus Johnson',
    email: 'marcus.johnson@company.com',
    jobRole: 'C1',
    manager: '5',
    about: 'Consultant - Backend Development',
  },
  {
    id: '13',
    name: 'Olivia Davis',
    email: 'olivia.davis@company.com',
    jobRole: 'SC1',
    manager: '6',
    about: 'Senior Consultant - Market Analysis',
  },
  {
    id: '14',
    name: 'Nathan Wilson',
    email: 'nathan.wilson@company.com',
    jobRole: 'C3',
    manager: '6',
    about: 'Consultant - Strategic Planning',
  },
];

// Single person (CEO only)
export const singlePersonData: User[] = [
  {
    id: '1',
    name: 'Victoria Sterling',
    email: 'victoria.sterling@company.com',
    jobRole: 'P',
    manager: null,
    about: 'Founder and CEO',
  },
];

// Deep hierarchy (5+ levels)
export const deepHierarchyData: User[] = [
  {
    id: '1',
    name: 'William Thompson',
    email: 'william.thompson@company.com',
    jobRole: 'P',
    manager: null,
    about: 'Partner',
  },
  {
    id: '2',
    name: 'Elizabeth Moore',
    email: 'elizabeth.moore@company.com',
    jobRole: 'SM',
    manager: '1',
    about: 'Senior Manager',
  },
  {
    id: '3',
    name: 'Charles Jackson',
    email: 'charles.jackson@company.com',
    jobRole: 'M',
    manager: '2',
    about: 'Manager',
  },
  {
    id: '4',
    name: 'Margaret Taylor',
    email: 'margaret.taylor@company.com',
    jobRole: 'SC2',
    manager: '3',
    about: 'Senior Consultant',
  },
  {
    id: '5',
    name: 'Henry Adams',
    email: 'henry.adams@company.com',
    jobRole: 'C3',
    manager: '4',
    about: 'Consultant',
  },
  {
    id: '6',
    name: 'Catherine Wright',
    email: 'catherine.wright@company.com',
    jobRole: 'C1',
    manager: '5',
    about: 'Junior Consultant',
  },
];

// Wide hierarchy (many siblings at same level)
export const wideHierarchyData: User[] = [
  {
    id: '1',
    name: 'Richard Foster',
    email: 'richard.foster@company.com',
    jobRole: 'P',
    manager: null,
    about: 'Partner',
  },
  {
    id: '2',
    name: 'Anna Peterson',
    email: 'anna.peterson@company.com',
    jobRole: 'M',
    manager: '1',
    about: 'Manager - Team A',
  },
  {
    id: '3',
    name: 'Brian Collins',
    email: 'brian.collins@company.com',
    jobRole: 'SC2',
    manager: '2',
    about: 'Senior Consultant',
  },
  {
    id: '4',
    name: 'Caroline Hughes',
    email: 'caroline.hughes@company.com',
    jobRole: 'SC1',
    manager: '2',
    about: 'Senior Consultant',
  },
  {
    id: '5',
    name: 'Derek Murphy',
    email: 'derek.murphy@company.com',
    jobRole: 'C3',
    manager: '2',
    about: 'Consultant',
  },
  {
    id: '6',
    name: 'Emma Richardson',
    email: 'emma.richardson@company.com',
    jobRole: 'C2',
    manager: '2',
    about: 'Consultant',
  },
  {
    id: '7',
    name: 'Frank Cooper',
    email: 'frank.cooper@company.com',
    jobRole: 'C1',
    manager: '2',
    about: 'Consultant',
  },
  {
    id: '8',
    name: 'Grace Bennett',
    email: 'grace.bennett@company.com',
    jobRole: 'C1',
    manager: '2',
    about: 'Consultant',
  },
];

// Two top-level partners with their respective teams
export const dualPartnershipData: User[] = [
  // Partner 1 and their team
  {
    id: '1',
    name: 'Victoria Sterling',
    email: 'victoria.sterling@company.com',
    jobRole: 'P',
    manager: null,
    about: 'Managing Partner - Technology Division',
  },
  {
    id: '2',
    name: 'James Morrison',
    email: 'james.morrison@company.com',
    jobRole: 'SM',
    manager: '1',
    about: 'Senior Manager - Cloud & Infrastructure',
  },
  {
    id: '3',
    name: 'Sarah Kim',
    email: 'sarah.kim@company.com',
    jobRole: 'M',
    manager: '2',
    about: 'Manager - DevOps Team',
  },
  {
    id: '4',
    name: 'Michael Chen',
    email: 'michael.chen@company.com',
    jobRole: 'SC1',
    manager: '3',
    about: 'Senior Consultant - Platform Engineering',
  },
  {
    id: '5',
    name: 'Emma Rodriguez',
    email: 'emma.rodriguez@company.com',
    jobRole: 'C3',
    manager: '3',
    about: 'Consultant - Site Reliability Engineer',
  },

  // Partner 2 and their team
  {
    id: '6',
    name: 'Alexander Cross',
    email: 'alexander.cross@company.com',
    jobRole: 'P',
    manager: null,
    about: 'Managing Partner - Strategy & Operations',
  },
  {
    id: '7',
    name: 'Diana Wells',
    email: 'diana.wells@company.com',
    jobRole: 'SM',
    manager: '6',
    about: 'Senior Manager - Business Transformation',
  },
  {
    id: '8',
    name: 'Robert Lynch',
    email: 'robert.lynch@company.com',
    jobRole: 'M',
    manager: '7',
    about: 'Manager - Process Optimization',
  },
  {
    id: '9',
    name: 'Lisa Wang',
    email: 'lisa.wang@company.com',
    jobRole: 'SC2',
    manager: '8',
    about: 'Senior Consultant - Change Management',
  },
  {
    id: '10',
    name: 'David Park',
    email: 'david.park@company.com',
    jobRole: 'C2',
    manager: '8',
    about: 'Consultant - Data Analytics',
  },
  {
    id: '11',
    name: 'Rachel Green',
    email: 'rachel.green@company.com',
    jobRole: 'M',
    manager: '7',
    about: 'Manager - Strategic Planning',
  },
  {
    id: '12',
    name: 'Thomas Hill',
    email: 'thomas.hill@company.com',
    jobRole: 'SC1',
    manager: '11',
    about: 'Senior Consultant - Market Research',
  },
];

// Team with detailed long descriptions for testing text overflow
export const detailedDescriptionsData: User[] = [
  {
    id: '1',
    name: 'Dr. Margaret Thompson',
    email: 'margaret.thompson@company.com',
    jobRole: 'P',
    manager: null,
    about: 'Partner and Chief Technology Officer with over 20 years of experience in enterprise software architecture, digital transformation, and strategic technology leadership. Specializes in cloud-native solutions, microservices architecture, and leading large-scale technology implementations across Fortune 500 companies.',
  },
  {
    id: '2',
    name: 'Alexander Rodriguez',
    email: 'alexander.rodriguez@company.com',
    jobRole: 'SM',
    manager: '1',
    about: 'Senior Manager leading the Cloud Infrastructure practice. Expert in AWS, Azure, and GCP with extensive experience in DevOps, CI/CD pipelines, infrastructure as code, Kubernetes orchestration, and enterprise security frameworks. Previously led digital transformation initiatives at three major consulting firms.',
  },
  {
    id: '3',
    name: 'Jennifer Liu',
    email: 'jennifer.liu@company.com',
    jobRole: 'M',
    manager: '2',
    about: 'Manager focused on AI/ML solutions and data engineering platforms. PhD in Computer Science with research background in machine learning algorithms. Leads projects involving predictive analytics, natural language processing, computer vision, and big data processing using Spark, Kafka, and TensorFlow.',
  },
  {
    id: '4',
    name: 'David Park',
    email: 'david.park@company.com',
    jobRole: 'SC1',
    manager: '3',
    about: 'Senior Consultant specializing in machine learning model deployment, MLOps pipelines, and AI ethics. Certifications in AWS ML, Google Cloud AI, and Azure AI. Experience with PyTorch, scikit-learn, Docker, Kubernetes, and building scalable ML inference systems.',
  },
  {
    id: '5',
    name: 'Rachel Kumar',
    email: 'rachel.kumar@company.com',
    jobRole: 'SC2',
    manager: '2',
    about: 'Senior Consultant with expertise in cybersecurity, zero-trust architecture, and compliance frameworks including SOC2, HIPAA, and GDPR. Certified in CISSP and CISM with experience in penetration testing, security audits, and incident response planning.',
  },
  {
    id: '6',
    name: 'Michael Johnson',
    email: 'michael.johnson@company.com',
    jobRole: 'C3',
    manager: '3',
    about: 'Short description for comparison.',
  },
];

// Empty data for testing
export const emptyData: User[] = [];
